/* Parcours : liens sans barre finale, transitions de page, onglet actif, fiche chargée à part. */
import { chromium } from "@playwright/test";
import { servir } from "./serveur.mjs";
const srv = servir(new URL("../../out/", import.meta.url).pathname, 8803);
const etat = { A: { objectif: 0, materiel: 0, acc: [] }, LOG: {}, SWAP: {}, SWAPP: {}, PLAN: null, SEANCES: [{ nom: "Test", ex: [{ id: "dc", s: 3, r: 8, p: "2 min" }] }], wk: 0, day: 0, FINI: false, ts: Date.now() };
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
await ctx.addInitScript((s) => { if (!localStorage.getItem("palier.state.v1")) localStorage.setItem("palier.state.v1", JSON.stringify(s)); }, etat);
await ctx.route(/supabase\.co/, (r) => r.abort());
const pg = await ctx.newPage();
const errs = []; pg.on("pageerror", (e) => errs.push(e.message));
let fiches = 0; pg.on("request", (r) => r.url().includes("fiches.json") && fiches++);
await pg.addInitScript(() => {
  window.__vt = 0;
  const o = document.startViewTransition?.bind(document);
  if (o) document.startViewTransition = (...a) => { window.__vt++; return o(...a); };
});
const ok = (c, m) => { console.log(c ? "OK  " : "ÉCHEC", m); if (!c) process.exitCode = 1; };
await pg.goto("http://localhost:8803/");
await pg.waitForURL(/\/seances\/$/);
ok(await pg.locator('nav a[aria-current="page"]').textContent() === "Séances", "onglet Séances actif");
await pg.getByText("Test", { exact: true }).click();
await pg.waitForURL(/\/seances\/seance\/\?i=0/);
ok((await pg.evaluate(() => window.__vt)) >= 1, "transition de page déclenchée");
await pg.locator("button", { hasText: "Séances" }).first().click();
await pg.waitForURL(/\/seances\/$/);
await pg.getByText("Créer une séance pour moi").click();
await pg.waitForURL(/\/seances\/assistant\/$/);
ok(true, "assistant ouvert");
await pg.locator("nav a", { hasText: "Explorer" }).click();
await pg.waitForURL(/\/explorer\/$/);
ok(await pg.locator('nav a[aria-current="page"]').textContent() === "Explorer", "onglet Explorer actif");
ok(fiches === 0, "fiches.json pas chargé avant d'ouvrir une fiche");
await pg.goto("http://localhost:8803/seances/seance/?i=0");
await pg.locator("article button, li button, div > button").filter({ hasText: /Développé couché/ }).first().click();
await pg.getByRole("button", { name: "Fiche" }).click();
await pg.getByText("Exécution").waitFor({ timeout: 5000 });
ok(fiches === 1, "fiches.json chargé à l'ouverture de la fiche, textes affichés");
console.log("erreurs:", JSON.stringify(errs));
await b.close(); srv.close();
